# Site settings
title:          J U W E S B M
description:    "Juventude Wesleyana de Barra Mansa"

url:            "https://romeroalmeida.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Romero Almeida
  url:          https://instagram.com/romeroalmeida7
  email:        romerobm@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       4

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
